SysLink: Headers - Fix C++ compilation errors for SysLink headers
When SysLink headers are compiled for c++ code, the following error
is thrown:

error: '<anonymous>' has incomplete type
error: invalid use of 'Void'

for functions that take zero arguments.
This patch fixes it by using 'void' instead of 'Void'for such functions.

Also added cosmetic change in function declaration of
UsrUtilsDrv_destroy()

Signed-off-by: Subramaniam C.A <subramaniam.ca@ti.com>
Signed-off-by: Jorge E. Solano <jsolano@ti.com>